@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name" : "Cristian Camargo",
    "email" : "contato@camargodev.com",
    "password" : "1234567"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "email" : "contato@camargodev.com",
    "password" : "1234567"
}

###

# @name create_questions
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "title" : "Por que estudar NestJs 3",
    "content" :  "conteudo da pergunta"
}


###

# @name fetch_recent_questions
GET {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}